// 三个生成器：napi 绑定源码 / .d.ts / JSON Schema（ADR-004 §4.3）

function cppType(t) {
  switch (t) {
    case 'string': return 'const std::string&';
    case 'float': return 'float';
    case 'int': return 'int';
    case 'bool': return 'bool';
    default: return t;
  }
}

export function generateNapi(ir) {
  const mod = ir.module.replace(/\./g, '_');
  const L = [];
  L.push('// Auto-generated by ccx-bindgen (灯塔任务 C 原型). DO NOT EDIT.');
  L.push('#include <node_api.h>');
  L.push('#include <string>');
  L.push('#include <vector>');
  L.push('');
  L.push('namespace ' + mod + ' {');
  L.push('// 占位实现：bindgen 只生成桥接骨架；实现体由引擎/业务代码替换');
  for (const cls of ir.classes) {
    for (const m of cls.methods) {
      const plist = m.params.map((p) => cppType(p.type) + ' ' + p.name).join(', ');
      const ret =
        m.ret === 'string' ? 'const char*' : m.ret === 'void' ? 'void' : cppType(m.ret);
      const body =
        m.ret === 'string' ? 'return "TODO";' : m.ret === 'void' ? '' : 'return 0;';
      L.push('  ' + ret + ' ' + m.name + '(' + plist + ') { ' + body + ' }');
    }
    for (const p of cls.props) {
      const lit = typeof p.default === 'string' ? '"' + p.default + '"' : String(p.default ?? 0);
      L.push('  const ' + p.type + ' ' + p.name + '_value = ' + lit + ';');
    }
  }
  L.push('}  // namespace ' + mod);
  L.push('');

  for (const cls of ir.classes) {
    for (const m of cls.methods) {
      L.push('static napi_value ' + m.name + '_wrapper(napi_env env, napi_callback_info info) {');
      L.push('  size_t argc = ' + Math.max(1, m.params.length) + ';');
      L.push('  napi_value args[' + Math.max(1, m.params.length) + '];');
      L.push('  napi_get_cb_info(env, info, &argc, args, nullptr, nullptr);');
      const callArgs = [];
      m.params.forEach((p, i) => {
        if (p.type === 'string') {
          L.push('  size_t len' + i + ' = 0; napi_get_value_string_utf8(env, args[' + i + '], nullptr, 0, &len' + i + ');');
          L.push('  std::vector<char> buf' + i + '(len' + i + ' + 1);');
          L.push('  napi_get_value_string_utf8(env, args[' + i + '], buf' + i + '.data(), buf' + i + '.size(), &len' + i + ');');
          L.push('  const std::string s' + i + '(buf' + i + '.data(), len' + i + ');');
          callArgs.push('s' + i);
        } else {
          L.push('  double d' + i + ' = 0; napi_get_value_double(env, args[' + i + '], &d' + i + ');');
          L.push('  ' + cppType(p.type) + ' v' + i + ' = (' + cppType(p.type) + ')d' + i + ';');
          callArgs.push('v' + i);
        }
      });
      const call = mod + '::' + m.name + '(' + callArgs.join(', ') + ')';
      if (m.ret === 'string') {
        L.push('  const std::string out = ' + call + ';');
        L.push('  napi_value result;');
        L.push('  napi_create_string_utf8(env, out.c_str(), out.size(), &result);');
        L.push('  return result;');
      } else if (m.ret === 'void') {
        L.push('  ' + call + ';');
        L.push('  return nullptr;');
      } else {
        L.push('  const double out = static_cast<double>(' + call + ');');
        L.push('  napi_value result;');
        L.push('  napi_create_double(env, out, &result);');
        L.push('  return result;');
      }
      L.push('}');
      L.push('');
    }
  }

  L.push('static napi_value Init(napi_env env, napi_value exports) {');
  for (const cls of ir.classes) {
    const obj = 'cls_' + cls.name;
    L.push('  napi_value ' + obj + '; napi_create_object(env, &' + obj + ');');
    for (const m of cls.methods) {
      L.push('  napi_value fn_' + m.name + ';');
      L.push('  napi_create_function(env, "' + m.name + '", NAPI_AUTO_LENGTH, ' + m.name + '_wrapper, nullptr, &fn_' + m.name + ');');
      L.push('  napi_set_named_property(env, ' + obj + ', "' + m.name + '", fn_' + m.name + ');');
    }
    for (const p of cls.props) {
      L.push('  napi_value pv_' + p.name + ';');
      if (p.type === 'string') {
        L.push('  napi_create_string_utf8(env, ' + mod + '::' + p.name + '_value, NAPI_AUTO_LENGTH, &pv_' + p.name + ');');
      } else {
        L.push('  napi_create_double(env, ' + mod + '::' + p.name + '_value, &pv_' + p.name + ');');
      }
      L.push('  napi_set_named_property(env, ' + obj + ', "' + p.name + '", pv_' + p.name + ');');
    }
    L.push('  napi_set_named_property(env, exports, "' + cls.name + '", ' + obj + ');');
  }
  L.push('  return exports;');
  L.push('}');
  L.push('');
  L.push('NAPI_MODULE(NODE_GYP_MODULE_NAME, Init)');
  L.push('');
  return L.join('\n');
}

export function generateDts(ir) {
  const out = [];
  out.push('// Auto-generated by ccx-bindgen (灯塔任务 C 原型). DO NOT EDIT.');
  for (const cls of ir.classes) {
    out.push('');
    out.push('declare namespace ' + ir.module + ' {');
    if (cls.doc) out.push('  /** ' + cls.doc + ' */');
    out.push('  class ' + cls.name + ' {');
    for (const p of cls.props) {
      // ambient 上下文禁止初始化器；默认值只记录在 schema（生成器保留信息）
      out.push('    /** 默认值: ' + (p.default ?? '-') + ' */');
      out.push('    readonly ' + p.name + ': ' + mapType(p.type) + ';');
    }
    for (const m of cls.methods) {
      if (m.doc) out.push('    /** ' + m.doc + ' */');
      const ps = m.params.map((p) => p.name + ': ' + mapType(p.type)).join(', ');
      out.push('    ' + m.name + '(' + ps + '): ' + mapType(m.ret) + ';');
    }
    out.push('  }');
    out.push('}');
  }
  return out.join('\n');
}

function mapType(t) {
  switch (t) {
    case 'float': return 'number';
    case 'int': return 'number';
    case 'bool': return 'boolean';
    case 'void': return 'void';
    case 'string': return 'string';
    default: return t;
  }
}

export function generateSchema(ir) {
  const classes = {};
  for (const cls of ir.classes) {
    const methods = {};
    for (const m of cls.methods) {
      const params = {};
      for (const p of m.params) params[p.name] = { type: mapType(p.type) };
      methods[m.name] = { doc: m.doc ?? undefined, params, returns: mapType(m.ret) };
    }
    const properties = {};
    for (const p of cls.props) {
      properties[p.name] = { type: mapType(p.type), readOnly: true, default: p.default ?? undefined };
    }
    classes[cls.name] = { title: cls.name, doc: cls.doc ?? undefined, type: 'object', properties, methods };
  }
  return JSON.stringify(
    { $schema: 'http://json-schema.org/draft-07/schema#', title: ir.module, classes },
    null, 2,
  ) + '\n';
}
