// 三个生成器：napi 绑定源码 / .d.ts / JSON Schema（ADR-004 §4.3；灯塔 C v0.2）
import { analyzeType } from './idl.mjs';

function cppType(t) {
  switch (t) {
    case 'string': return 'const std::string&';
    case 'float': return 'float';
    case 'int': return 'int';
    case 'bool': return 'bool';
    default: return t;
  }
}

function mapType(t) {
  switch (t) {
    case 'float': return 'number';
    case 'int': return 'number';
    case 'bool': return 'boolean';
    case 'void': return 'void';
    case 'string': return 'string';
    default: return t;
  }
}

function defaultLit(p) {
  if (p.def === null) return null;
  if (p.def === true) return 'true';
  if (p.def === false) return 'false';
  if (typeof p.def === 'number') return String(p.def);
  return '"' + p.def + '"';
}

export function generateNapi(ir) {
  const mod = ir.module.replace(/\./g, '_');
  const L = [];
  L.push('// Auto-generated by ccx-bindgen (灯塔任务 C 原型). DO NOT EDIT.');
  L.push('#include <node_api.h>');
  L.push('#include <string>');
  L.push('#include <vector>');
  L.push('');
  L.push('namespace ' + mod + ' {');
  L.push('// 占位实现：bindgen 只生成桥接骨架；实现体由引擎/业务代码替换');
  for (const cls of ir.classes) {
    for (const m of cls.methods) {
      const plist = m.params.map((p) => cppType(p.type) + ' ' + p.name).join(', ');
      const ret = m.ret === 'string' ? 'const char*' : m.ret === 'void' ? 'void' : cppType(m.ret);
      const body = m.ret === 'string' ? 'return "TODO";' : m.ret === 'void' ? '' : 'return 0;';
      L.push('  ' + ret + ' ' + m.name + '(' + plist + ') { ' + body + ' }');
    }
    for (const p of cls.props) {
      const lit = typeof p.default === 'string' ? '"' + p.default + '"' : String(p.default ?? 0);
      L.push('  const ' + p.type + ' ' + p.name + '_value = ' + lit + ';');
    }
  }
  L.push('}  // namespace ' + mod);
  L.push('');

  // 回调参数存储（每个方法每个回调一个 napi_ref）
  for (const cls of ir.classes) {
    for (const m of cls.methods) {
      for (const p of m.params) {
        const a = analyzeType(p.type);
        if (a.kind === 'callback') {
          L.push('static napi_ref g_ref_' + m.name + '_' + p.name + ' = nullptr;');
        }
      }
    }
  }
  if (ir.classes.some((c) => c.methods.some((m) => m.params.some((p) =>
      analyzeType(p.type).kind === 'callback')))) {
    L.push('');
  }

  for (const cls of ir.classes) {
    for (const m of cls.methods) {
      L.push('static napi_value ' + m.name + '_wrapper(napi_env env, napi_callback_info info) {');
      L.push('  size_t argc = ' + Math.max(1, m.params.length) + ';');
      L.push('  napi_value args[' + Math.max(1, m.params.length) + '];');
      L.push('  napi_get_cb_info(env, info, &argc, args, nullptr, nullptr);');
      const callArgs = [];
      m.params.forEach((p, i) => {
        const a = analyzeType(p.type);
        const lit = defaultLit(p);
        if (a.kind === 'callback') {
          // 存储回调引用；实现体经 g_ref_<m>_<p> 调用（骨架只做生命周期保存）
          L.push('  if (argc > ' + i + ' && args[' + i + '] != nullptr) {');
          L.push('    napi_create_reference(env, args[' + i + '], 1, &g_ref_' + m.name + '_' + p.name + ');');
          L.push('  }');
        } else if (a.kind === 'array') {
          const cppEl = a.base === 'string' ? 'std::string' : 'float';
          L.push('  std::vector<' + cppEl + '> v' + i + ';');
          L.push('  if (argc > ' + i + ') {');
          L.push('    uint32_t n' + i + ' = 0; napi_get_array_length(env, args[' + i + '], &n' + i + ');');
          L.push('    for (uint32_t k = 0; k < n' + i + '; ++k) {');
          L.push('      napi_value el' + i + '; napi_get_element(env, args[' + i + '], k, &el' + i + ');');
          if (a.base === 'string') {
            L.push('      size_t ln = 0; napi_get_value_string_utf8(env, el' + i + ', nullptr, 0, &ln);');
            L.push('      std::vector<char> bf(ln + 1);');
            L.push('      napi_get_value_string_utf8(env, el' + i + ', bf.data(), bf.size(), &ln);');
            L.push('      v' + i + '.emplace_back(bf.data(), ln);');
          } else {
            L.push('      double dv = 0; napi_get_value_double(env, el' + i + ', &dv);');
            L.push('      v' + i + '.push_back(static_cast<float>(dv));');
          }
          L.push('    }');
          L.push('  }');
          callArgs.push('v' + i);
        } else if (a.base === 'string') {
          L.push('  std::string s' + i + (lit !== null ? ' = ' + lit : '') + ';');
          L.push('  if (argc > ' + i + ') {');
          L.push('    size_t len' + i + ' = 0; napi_get_value_string_utf8(env, args[' + i + '], nullptr, 0, &len' + i + ');');
          L.push('    std::vector<char> buf' + i + '(len' + i + ' + 1);');
          L.push('    napi_get_value_string_utf8(env, args[' + i + '], buf' + i + '.data(), buf' + i + '.size(), &len' + i + ');');
          L.push('    s' + i + '.assign(buf' + i + '.data(), len' + i + ');');
          L.push('  }');
          callArgs.push('s' + i);
        } else {
          L.push('  double d' + i + ' = ' + (lit !== null ? lit : '0') + ';');
          L.push('  if (argc > ' + i + ') napi_get_value_double(env, args[' + i + '], &d' + i + ');');
          L.push('  ' + cppType(a.base) + ' v' + i + ' = (' + cppType(a.base) + ')d' + i + ';');
          callArgs.push('v' + i);
        }
      });
      const call = mod + '::' + m.name + '(' + callArgs.join(', ') + ')';
      if (m.ret === 'string') {
        L.push('  const std::string out = ' + call + ';');
        L.push('  napi_value result;');
        L.push('  napi_create_string_utf8(env, out.c_str(), out.size(), &result);');
        L.push('  return result;');
      } else if (m.ret === 'void') {
        L.push('  ' + call + ';');
        L.push('  return nullptr;');
      } else {
        L.push('  const double out = static_cast<double>(' + call + ');');
        L.push('  napi_value result;');
        L.push('  napi_create_double(env, out, &result);');
        L.push('  return result;');
      }
      L.push('}');
      L.push('');
    }
  }

  L.push('static napi_value Init(napi_env env, napi_value exports) {');
  for (const cls of ir.classes) {
    const obj = 'cls_' + cls.name;
    L.push('  napi_value ' + obj + '; napi_create_object(env, &' + obj + ');');
    for (const m of cls.methods) {
      L.push('  napi_value fn_' + m.name + ';');
      L.push('  napi_create_function(env, "' + m.name + '", NAPI_AUTO_LENGTH, ' + m.name + '_wrapper, nullptr, &fn_' + m.name + ');');
      L.push('  napi_set_named_property(env, ' + obj + ', "' + m.name + '", fn_' + m.name + ');');
    }
    for (const p of cls.props) {
      L.push('  napi_value pv_' + p.name + ';');
      if (p.type === 'string') {
        L.push('  napi_create_string_utf8(env, ' + mod + '::' + p.name + '_value, NAPI_AUTO_LENGTH, &pv_' + p.name + ');');
      } else {
        L.push('  napi_create_double(env, ' + mod + '::' + p.name + '_value, &pv_' + p.name + ');');
      }
      L.push('  napi_set_named_property(env, ' + obj + ', "' + p.name + '", pv_' + p.name + ');');
    }
    L.push('  napi_set_named_property(env, exports, "' + cls.name + '", ' + obj + ');');
  }
  L.push('  return exports;');
  L.push('}');
  L.push('');
  L.push('NAPI_MODULE(NODE_GYP_MODULE_NAME, Init)');
  L.push('');
  return L.join('\n');
}

function dtsType(p) {
  const a = analyzeType(p.type);
  if (a.kind === 'callback') {
    const ps = a.callbackParams.map((q) => q.name + ': ' + mapType(q.type)).join(', ');
    return '(' + ps + ') => ' + mapType(a.ret);
  }
  if (a.kind === 'array') return mapType(a.base) + '[]';
  return mapType(a.base);
}

export function generateDts(ir) {
  const out = [];
  out.push('// Auto-generated by ccx-bindgen (灯塔任务 C 原型). DO NOT EDIT.');
  for (const cls of ir.classes) {
    out.push('');
    out.push('declare namespace ' + ir.module + ' {');
    if (cls.doc) out.push('  /** ' + cls.doc + ' */');
    out.push('  class ' + cls.name + ' {');
    for (const p of cls.props) {
      out.push('    /** 默认值: ' + (p.default ?? '-') + ' */');
      out.push('    readonly ' + p.name + ': ' + mapType(p.type) + ';');
    }
    for (const m of cls.methods) {
      if (m.doc) out.push('    /** ' + m.doc + ' */');
      const ps = m.params.map((p) =>
        p.name + (p.def !== null ? '?' : '') + ': ' + dtsType(p)).join(', ');
      out.push('    ' + m.name + '(' + ps + '): ' + mapType(m.ret) + ';');
    }
    out.push('  }');
    out.push('}');
  }
  return out.join('\n');
}

function schemaTypeForType(type) {
  const a = analyzeType(type);
  if (a.kind === 'callback') {
    return { type: 'function', binding: 'callback' };
  }
  if (a.kind === 'array') {
    return { type: 'array', items: { type: mapType(a.base) } };
  }
  return { type: mapType(a.base) };
}

export function generateSchema(ir) {
  const classes = {};
  for (const cls of ir.classes) {
    const methods = {};
    for (const m of cls.methods) {
      const params = {};
      for (const p of m.params) {
        const s = schemaTypeForType(p.type);
        if (p.def !== null) s.default = p.def;
        params[p.name] = s;
      }
      methods[m.name] = { doc: m.doc ?? undefined, params, returns: mapType(m.ret) };
    }
    const properties = {};
    for (const p of cls.props) {
      properties[p.name] = { type: mapType(p.type), readOnly: true, default: p.default ?? undefined };
    }
    classes[cls.name] = { title: cls.name, doc: cls.doc ?? undefined, type: 'object', properties, methods };
  }
  return JSON.stringify(
    { $schema: 'http://json-schema.org/draft-07/schema#', title: ir.module, classes },
    null, 2,
  ) + '\n';
}
